spring:
    profiles: test
name: test-YAML
environment: test
servers: 
    - www.abc.test.com
    - www.xyz.test.com
 
---
spring:
    profiles: development
name: development-YAML
environment: development
servers: 
    - www.abc.com
    - www.xyz.com
